version: '3.4'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: SportCompetitionsAPI
      dockerfile: SportCompetitionsAPI.Controllers/Dockerfile # Тут обязательно должен быть путь такого типа
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:8080
    ports:
      - "9000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - database
    networks:
      - default

  client:
    image: client
    container_name: client
    build:
      context: SportCompetitionsWeb
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    networks:
      - default

  proxy:
    image: nginx:mainline
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
     - backend  
     - client  
    networks:
      - default

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    user: root
    volumes:
      - "database-data:/var/opt/mssql/data/"
      - "database-data:/var/opt/mssql/log/"
      - "database-data:/var/opt/mssql/secrets/"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    networks:
      - default

volumes:
  database-data:


networks:
  default:
    driver: bridge
